### PR TITLE
Fix loadcase string input

### LINKED ISSUE #99: loadcase does not load file if defined as string
loadcase fails to load matpower file if the case is defined by a `string`. It loads the case if the case is defined as `char`.
e.g.: 
```matlab
loadcase('case5.m')        % ok
loadcase("case5.m")       % fail
Error using loadcase (line 217)

loadcase: input arg should be a struct or a string containing a filename
```

I think either the corresponding error message should be changed or support added to `string`.

### PR DESCRIPTION
**Pull request by timonviola**
Closes #99

Fix issue #99 
Proposes a minimal fix to enable passing cases defined by `string` variables.
Now the following works:
```matlab
loadcase(pwd + "/.data/case14_tightened.m")
```

### CODE REVIEW

File: lib/loadcase.m [hunk 1]
```diff
@@ -50,6 +50,9 @@
 end
 
 %%-----  read data into struct  -----
+if isstring(casefile)
```
Comment (rdzman) [inline lib/loadcase.m:53]:
```suggestion
if isa(casefile, 'string')
```

Comment (rdzman) [reply lib/loadcase.m:53]: Thanks Timon.

Looks like strings were introduced in Matlab R2017a. For Octave, as far as I can tell strings are still not implemented and `isstring()` was only added in version 4.4.

So, I think the suggested change here would take care of backward compatibility.

Comment (rdzman) [reply lib/loadcase.m:53]: And it would probably be good to update the error message to ...
```
input arg should be a struct or a char array/string containing a filename
```
